version: "3"
services:
  chapter0:
    container_name: api-mystery-chapter-0
    image: snowetiger/api-mystery-chapter-0:0.2.2
    ports:
    - 8080:80
    networks:
    - backend
networks:
  backend:
    driver: bridge
