@hostname = localhost
@port = 5000
@host = http://{{hostname}}:{{port}}/getfitnow/api
@token = d901050d-07ec-4990-a05c-ab2178e2e09c

### Get event
@membership_id = 4KB72
GET {{host}}/membership/{{membership_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}