@hostname = localhost
@port = 5000
@host = http://{{hostname}}:{{port}}/police/api
@hostAuth = http://{{hostname}}:{{port}}/police/auth

### Login
# @name login_user
POST {{hostAuth}}/login HTTP/1.1
Content-Type: application/json

{
    "login": "ApiFox",
    "password": "Fox2025"
}

###
@token = {{login_user.response.body.token}}

### Get all persons
GET {{host}}/person/all HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Search by name 
POST {{host}}/person/search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Peteuil"
}

### Search by license_id 
POST {{host}}/person/search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "license_id": "993845"
}

### Search by adress and license 
POST {{host}}/person/search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "license_id": 729987,
    "address": "Circle"
}


### Get all driver licenses
GET {{host}}/driver_license/all HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Get driver licenses by id
@id = 100280
GET {{host}}/driver_license/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Search by age 
POST {{host}}/driver_license/search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "age": 72
}

### Search by adress and license 
POST {{host}}/driver_license/search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "eye_color": "brown",
    "hair_color": "red"
}
