@hostname = localhost
@port = 5000
@host = http://{{hostname}}:{{port}}/police/api
@hostAuth = http://{{hostname}}:{{port}}/police/auth

### Login
# @name login_user
POST {{hostAuth}}/login HTTP/1.1
Content-Type: application/json

{
    "login": "ApiFox",
    "password": "Fox2025"
}

###
@token = {{login_user.response.body.token}}

### Get all persons
GET {{host}}/person/all HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Search by name 
POST {{host}}/person/search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Ivan Petrov"
}

### Search by license_id 
POST {{host}}/person/search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "driver_license": "961137"
}

### Get all driver licenses
GET {{host}}/driver_license/all HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Get driver licenses by id
@id = 961137
GET {{host}}/driver_license/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Search by age 
POST {{host}}/driver_license/search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "age": 72
}

### Get car by filters
@person_id = 99991
POST {{host}}/car/search HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "plate_number": "9KA",
    "car_make": "Volkswagen",
    "car_model": "Rabbit"
}

### Get car by filters
@plate = 9ka
GET {{host}}/car/{{plate}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
